-- select * from Paciente

BEGIN TRAN
	UPDATE Paciente SET apellido = 'Ramos' WHERE idPaciente = 5
	IF @@ROWCOUNT = 1 --VERIFICA QUE EN LA CONSULTA ANTERIOR SE ALLA ACTUALIZADO UN UNICO REGISTRO
		COMMIT TRAN --CONFIRMA LA OPERACION
	ELSE
		ROLLBACK TRAN -- DESASE LA OPERACION ANTERIOR 


-- SELECT * FROM Turno
BEGIN TRANSACTION
	DELETE FROM Turno WHERE estado = 3
	IF @@ROWCOUNT = 1
		COMMIT TRANSACTION
	ELSE
		ROLLBACK TRANSACTION